run:
issues:
  exclude-use-default: false

linters:
  enable:
    - gocyclo
    - revive
  disable:
    - exhaustive
    - asciicheck
    - scopelint
    - gosec
    - varcheck    # deprecated
    - structcheck # deprecated
    - deadcode    #deprecated
    - rowserrcheck   # https://github.com/golangci/golangci-lint/issues/2649
    - sqlclosecheck  # https://github.com/golangci/golangci-lint/issues/2649
  presets:
    - bugs
    - unused
    - format

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    ignore: fmt:.*,io:^Read,^Close|^Write|^Shutdown
  revive:
    severity: warning
    confidence: 0.8